version: '3.4'

services:
  synergy.dataaccess.migrations:
    build:
      context: .
      dockerfile: Synergy.DataAccess.Migrations/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SYNERGY_CONSTR: "UserID=admin;Password=admin;Host=postgres-node;Port=5432;Database=postgres;"
    depends_on:
      - "postgres-node"

  postgres-node:
    image: postgres
    container_name: postgres-node
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin