// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetCampaignTypesQuery.#ctor(Synergy.DataAccess.Context.ISynergyContext,AutoMapper.IMapper)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetGeneralLandUseCodesQuery.#ctor(Synergy.DataAccess.Context.ISynergyContext,AutoMapper.IMapper)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetInternalLandUseCodesQuery.#ctor(Synergy.DataAccess.Context.ISynergyContext,AutoMapper.IMapper)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetPropertyDisplayStrategiesDictionaryQuery.#ctor(Synergy.DataAccess.Context.ISynergyContext,AutoMapper.IMapper)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetStatesDictionaryQuery.#ctor(Synergy.DataAccess.Context.ISynergyContext,AutoMapper.IMapper)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetUsersDictionaryQuery.#ctor(Synergy.DataAccess.Context.ISynergyContext,AutoMapper.IMapper)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "EF Core query", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetUsersDictionaryQuery.Search(System.String)~Synergy.DataAccess.Dictionaries.Queries.Interfaces.IGetUsersDictionaryQuery")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "It is acceptable.", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetCampaignTypesQuery.Search(System.String)~Synergy.DataAccess.Dictionaries.Queries.Interfaces.IGetCampaignTypesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "It is acceptable.", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetGeneralLandUseCodesQuery.Search(System.String)~Synergy.DataAccess.Dictionaries.Queries.Interfaces.IGetGeneralLandUseCodesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "It is acceptable.", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetInternalLandUseCodesQuery.Search(System.String)~Synergy.DataAccess.Dictionaries.Queries.Interfaces.IGetInternalLandUseCodesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "It is acceptable.", Scope = "member", Target = "~M:Synergy.DataAccess.Dictionaries.Queries.Queries.GetStatesDictionaryQuery.Search(System.String)~Synergy.DataAccess.Dictionaries.Queries.Interfaces.IGetStatesDictionaryQuery")]