// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Abstractions.AuditMapperExtension.ApplyAuditMembers``2(AutoMapper.IMappingExpression{``0,``1})~AutoMapper.IMappingExpression{``0,``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Abstractions.LambdaBuilder.AndAlso``1(System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}},System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}})~System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EF Core EntityTypeBuilder is not null", Scope = "member", Target = "~M:Synergy.DataAccess.Abstractions.LambdaBuilder.OrElse``1(System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}},System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}})~System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1.andAlsoPredicates")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._isSortAsc")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._skip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._sortSelector")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._take")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1.andAlsoPredicates")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1.includes")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._isSortAsc")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._skip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._sortSelector")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1._take")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "It is acceptable at this case.", Scope = "member", Target = "~F:Synergy.DataAccess.Abstractions.BaseQuery`1.includes")]