using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using Synergy.DataAccess.Entities;

namespace Synergy.DataAccess.Context.Mapping
{
    public class InternalLandUseCodeMap : IEntityTypeConfiguration<InternalLandUseCode>
    {
        public void Configure(EntityTypeBuilder<InternalLandUseCode> builder)
        {
            builder.HasKey(e => e.Id);

            // TODO add name
            builder.HasData(
              new InternalLandUseCode { Id = 1, Name = string.Empty, Description = "AGRICULTURAL-FARM", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 2, Name = string.Empty, Description = "COM-AIRPORT TERMINAL/HANGER OR BUS TERMINAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 3, Name = string.Empty, Description = "COM-ANIMAL CLINIC", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 4, Name = string.Empty, Description = "COM-APARTMENT RENTAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 5, Name = string.Empty, Description = "COM-AUDITORIUM/THEATER", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 6, Name = string.Empty, Description = "COM-AUTO RACING/HORSE TRACKS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 7, Name = string.Empty, Description = "COM-AUTOMOBILE CAR SALES & SERVICE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018 -12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 8, Name = string.Empty, Description = "COM-AUTOMOTIVE SERVICE STATION", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 9, Name = string.Empty, Description = "COM-BANK", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 10, Name = string.Empty, Description = "COM-BARS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 11, Name = string.Empty, Description = "COM-BOWLING ALLEYS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 12, Name = string.Empty, Description = "COM-CAMP GROUNDS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 13, Name = string.Empty, Description = "COM-CAR WASH", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 14, Name = string.Empty, Description = "COM-CHURCH & CHARITABLE LAND", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 15, Name = string.Empty, Description = "COM-CLUBS/LODGE HALLS/EVENT HALLS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 16, Name = string.Empty, Description = "COM-CONDO", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 17, Name = string.Empty, Description = "COM-CONVENIENCE STORE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 18, Name = string.Empty, Description = "COM-DAIRY/FEED LOT", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 19, Name = string.Empty, Description = "COM-DAYCARE - PRIVATE SCHOOL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 20, Name = string.Empty, Description = "COM-DOG/CAT KENNELS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 21, Name = string.Empty, Description = "COM-DRIVE-IN RESTAURANT OR FOOD SERVICE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 22, Name = string.Empty, Description = "COM-DRIVING RANGE/MINIATURE GOLF", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 23, Name = string.Empty, Description = "COM-DRY CLEANING PLANTS & LAUNDRIES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 24, Name = string.Empty, Description = "COM-FLORIST/GREENHOUSE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 25, Name = string.Empty, Description = "COM-FOOD SERVICE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 26, Name = string.Empty, Description = "COM-FOUNDRIES & HEAVY MANUF PLANTS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 27, Name = string.Empty, Description = "COM-FULL SERVICE BANKS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 28, Name = string.Empty, Description = "COM-FUNERAL HOMES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 29, Name = string.Empty, Description = "COM-GARAGES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 30, Name = string.Empty, Description = "COM-GAS STATION", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 31, Name = string.Empty, Description = "COM-GENERAL STORAGE/MINI-STORAGE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 32, Name = string.Empty, Description = "COM-GOLF COURSES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 33, Name = string.Empty, Description = "COM-GREENHOUSE/NURSERY", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 34, Name = string.Empty, Description = "COM-HEALTH CLUB/GYM", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 35, Name = string.Empty, Description = "COM-HOTELS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 36, Name = string.Empty, Description = "COM-INDUSTRIAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 37, Name = string.Empty, Description = "COM-INDUSTRIAL CONDO", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 38, Name = string.Empty, Description = "COM-LIGHT INDUSTRIAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 39, Name = string.Empty, Description = "COM-LODGE HALLS & AMUSEMENT PARKS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 40, Name = string.Empty, Description = "COM-MANUFACTURING HEAVY", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 41, Name = string.Empty, Description = "COM-MANUFACTURING LIGHT", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 42, Name = string.Empty, Description = "COM-MARINA", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 43, Name = string.Empty, Description = "COM-MARINE SERVICE FACILITIES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 44, Name = string.Empty, Description = "COM-MEDICAL CLINICS AND OFFICES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 45, Name = string.Empty, Description = "COM-MIXED USE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 46, Name = string.Empty, Description = "COM-MORTUARY/CEMETERY", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 47, Name = string.Empty, Description = "COM-MOTELS AND TOURIST CABINS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 48, Name = string.Empty, Description = "COM-NEIGHBORHOOD SHOPPING CENTER", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 49, Name = string.Empty, Description = "COM-NURSING HOMES & PRIV HOSPITALS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 50, Name = string.Empty, Description = "COM-OFFICE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 51, Name = string.Empty, Description = "COM-OFFICE BLDGS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 52, Name = string.Empty, Description = "COM-OFFICE CONDOMINIUMS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 53, Name = string.Empty, Description = "COM-OFFICE/APARTMENTS OVER", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 54, Name = string.Empty, Description = "COM-OFFICE/STORAGE OVER", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 55, Name = string.Empty, Description = "COM-OTHER COMMERCIAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 56, Name = string.Empty, Description = "COM-OTHER INDUSTRIAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 57, Name = string.Empty, Description = "COM-PARKING GARAGE, STRUCTURES & L", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 58, Name = string.Empty, Description = "COM-PARKING LOT, STRUCTURE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 59, Name = string.Empty, Description = "COM-RADIO/TV STATION", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 60, Name = string.Empty, Description = "COM-RECREATIONAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 61, Name = string.Empty, Description = "COM-REGIONAL SHOPPING CENTER", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 62, Name = string.Empty, Description = "COM-RESEARCH & CHEM LAB", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 63, Name = string.Empty, Description = "COM-RESTAURANT; CAFETERIA AND/OR BAR", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 64, Name = string.Empty, Description = "COM-RETAIL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 65, Name = string.Empty, Description = "COM-SELF-SERVE LAUDROMAT", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 66, Name = string.Empty, Description = "COM-SENIOR COMMUNITY", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 67, Name = string.Empty, Description = "COM-SERVICE SHOP", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 68, Name = string.Empty, Description = "COM-SHOPPING CENTER", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 69, Name = string.Empty, Description = "COM-SUPERMARKETS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 70, Name = string.Empty, Description = "COM-THEATERS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 71, Name = string.Empty, Description = "COM-TOURIST ATTRACTION", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 72, Name = string.Empty, Description = "COM-TRAILER OR MOBILE HOME PARK", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 73, Name = string.Empty, Description = "COM-TRUCK FARM EQUIP. SALES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 74, Name = string.Empty, Description = "COM-TRUCK TERMINALS", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 75, Name = string.Empty, Description = "COM-WAREHOUSE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 76, Name = string.Empty, Description = "COM-WAREHOUSES", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 77, Name = string.Empty, Description = "GOV-MUNICIPAL", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 78, Name = string.Empty, Description = "RES-CONDOMINIUM", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 79, Name = string.Empty, Description = "RES-FOUR FAMILY DWELLING", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 80, Name = string.Empty, Description = "RES-MH & LAND", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 81, Name = string.Empty, Description = "RES-SINGLE FAMILY DWELLING", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 82, Name = string.Empty, Description = "RES-SINGLE FAMILY RESIDENTIAL (RENTAL PROPERTIES)", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 83, Name = string.Empty, Description = "RES-THREE FAMILY DWELLING", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 84, Name = string.Empty, Description = "RES-TWO FAMILY DWELLING", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 85, Name = string.Empty, Description = "VACANT- COMMERCIAL LAND", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 86, Name = string.Empty, Description = "VACANT- INDUSTRIAL LAND", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 87, Name = string.Empty, Description = "VACANT- RESIDENTIAL LAND", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") },
              new InternalLandUseCode { Id = 88, Name = string.Empty, Description = "VACANT-NON-AG ACREAGE", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2018-12-25"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2018-12-25") });
        }
    }
}
