using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using Synergy.DataAccess.Entities;

namespace Synergy.DataAccess.Context.Mapping
{
    internal class PermissionMap : IEntityTypeConfiguration<Permission>
    {
        public void Configure(EntityTypeBuilder<Permission> builder)
        {
            builder.HasKey(e => e.Id);
            builder.Property(b => b.Id)
                   .ForNpgsqlUseSequenceHiLo();
            builder.HasData(
                new Permission { Id = 1, Action = "Landing.Dashboard.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 3, Action = "CRM.Records.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 4, Action = "CRM.Properties.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 5, Action = "CRM.Opportunities.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 6, Action = "CRM.Opportunities.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 9, Action = "CRM.Contacts.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 10, Action = "CRM.Contacts.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 12, Action = "CRM.Campaigns.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 13, Action = "CRM.Campaigns.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 14, Action = "CRM.CampaignsDataDump.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 15, Action = "CRM.CampaignComments.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 16, Action = "CRM.CampaignComments.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 17, Action = "CRM.RecordComments.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 18, Action = "CRM.RecordComments.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 19, Action = "Underwriting.Event.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 20, Action = "Underwriting.Event.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 21, Action = "Underwriting.Event.Lock", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 22, Action = "Underwriting.EventDataDump.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 23, Action = "Underwriting.EventAssignment.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 24, Action = "Underwriting.EventAssignment.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 25, Action = "Underwriting.EventDataCut.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 26, Action = "Underwriting.EventDataCut.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 27, Action = "Underwriting.EventBidList.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 28, Action = "Underwriting.EventBidList.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 29, Action = "Underwriting.EventBidList.Delete", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 30, Action = "Underwriting.EventResultsUpload.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 31, Action = "Underwriting.ReviewPage.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 32, Action = "Underwriting.ReviewPage.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 33, Action = "Underwriting.ReviewComments.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 34, Action = "Underwriting.ReviewComments.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 35, Action = "Underwriting.Attachments.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 36, Action = "Underwriting.Attachments.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 37, Action = "Underwriting.Attachments.Delete", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-19"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-19") },
                new Permission { Id = 38, Action = "Underwriting.PropertyProfile.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-27"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-27") },
                new Permission { Id = 39, Action = "Underwriting.PropertyProfile.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-02-27"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-02-27") },
                new Permission { Id = 40, Action = "Workflow.UnderwritingTaskType.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 41, Action = "Workflow.UnderwritingTaskType.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 42, Action = "Workflow.UnderwritingWorkflowType.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 43, Action = "Workflow.UnderwritingWorkflowType.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 44, Action = "Admin.User.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-10"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-10") },
                new Permission { Id = 45, Action = "Admin.User.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-10"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-10") },
                new Permission { Id = 46, Action = "Admin.Role.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-10"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-10") },
                new Permission { Id = 47, Action = "Admin.Role.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-10"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-10") },
                new Permission { Id = 48, Action = "Admin.CRMMailMerge.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 49, Action = "Admin.CRMMailMerge.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 50, Action = "Admin.CRMMailMerge.Delete", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 51, Action = "Admin.UnderwritingMailMerge.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 52, Action = "Admin.UnderwritingMailMerge.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 53, Action = "Admin.UnderwritingMailMerge.Delete", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 54, Action = "Underwriting.MailMerge.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 55, Action = "CRM.MailMerge.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-05-23"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-05-23") },
                new Permission { Id = 56, Action = "CRM.OpportunitySensitiveData.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-07-18"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-07-18") },
                new Permission { Id = 57, Action = "CRM.OpportunitySensitiveData.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-07-18"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-07-18") },
                new Permission { Id = 58, Action = "Processing.Loan.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-07-22"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-07-22") },
                new Permission { Id = 59, Action = "Processing.Loan.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-07-22"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-07-22") },
                new Permission { Id = 60, Action = "Workflow.ProcessingTaskType.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 61, Action = "Workflow.ProcessingTaskType.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 62, Action = "Workflow.ProcessingWorkflowType.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 63, Action = "Workflow.ProcessingWorkflowType.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-03-01"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-03-01") },
                new Permission { Id = 64, Action = "CRM.Reminder.Read", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-11-11"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-11-11") },
                new Permission { Id = 65, Action = "CRM.Reminder.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-11-11"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-11-11") },
                new Permission { Id = 66, Action = "CRM.Properties.Write", CreatedById = Common.Constants.User.SystemUserId, CreatedOn = DateTime.Parse("2019-11-11"), ModifiedById = Common.Constants.User.SystemUserId, ModifiedOn = DateTime.Parse("2019-11-11") });
        }
    }
}
